<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="4" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-29T21:39:58 IDT" name="Surefire suite" finished-at="2025-04-29T21:40:42 IDT" duration-ms="43991">
    <groups>
    </groups>
    <test started-at="2025-04-29T21:39:58 IDT" name="Surefire test" finished-at="2025-04-29T21:40:42 IDT" duration-ms="43991">
      <class name="SignedUrlTests">
        <test-method signature="generateSignedUrlTest()[pri:1, instance:SignedUrlTests@58c1c010]" started-at="2025-04-29T21:40:17 IDT" name="generateSignedUrlTest" finished-at="2025-04-29T21:40:20 IDT" duration-ms="2053" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateSignedUrlTest -->
        <test-method signature="verifyAccessToSignedUrlTest()[pri:2, instance:SignedUrlTests@58c1c010]" started-at="2025-04-29T21:40:20 IDT" name="verifyAccessToSignedUrlTest" finished-at="2025-04-29T21:40:31 IDT" depends-on-methods="SignedUrlTests.generateSignedUrlTest" duration-ms="11748" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccessToSignedUrlTest -->
      </class> <!-- SignedUrlTests -->
      <class name="ObjectListTests">
        <test-method signature="TestPrivateObjectExisitsAndNotLoad()[pri:0, instance:ObjectListTests@6a472554]" started-at="2025-04-29T21:40:02 IDT" name="TestPrivateObjectExisitsAndNotLoad" finished-at="2025-04-29T21:40:15 IDT" duration-ms="12936" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestPrivateObjectExisitsAndNotLoad -->
        <test-method signature="testPublicObjectExistsAndLoadsInBrowser()[pri:0, instance:ObjectListTests@6a472554]" started-at="2025-04-29T21:40:15 IDT" name="testPublicObjectExistsAndLoadsInBrowser" finished-at="2025-04-29T21:40:17 IDT" duration-ms="2444" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Public file did not load successfully expected [200] but found [403]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Public file did not load successfully expected [200] but found [403]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at ObjectListTests.testPublicObjectExistsAndLoadsInBrowser(ObjectListTests.java:81)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:169)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:88)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPublicObjectExistsAndLoadsInBrowser -->
      </class> <!-- ObjectListTests -->
      <class name="DeleteItemTest">
        <test-method signature="testDeleteObjectAndVerifyInaccessible()[pri:0, instance:DeleteItemTest@70b0b186]" started-at="2025-04-29T21:39:58 IDT" name="testDeleteObjectAndVerifyInaccessible" finished-at="2025-04-29T21:40:02 IDT" duration-ms="4379" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[gcloud delete command failed expected [0] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: gcloud delete command failed expected [0] but found [1]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at DeleteItemTest.testDeleteObjectAndVerifyInaccessible(DeleteItemTest.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:565)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:155)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:169)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:88)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:137)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeleteObjectAndVerifyInaccessible -->
      </class> <!-- DeleteItemTest -->
      <class name="UpdateAccessTests">
        <test-method signature="testUpdateAccessPublicToPrivate()[pri:0, instance:UpdateAccessTests@b7f23d9]" started-at="2025-04-29T21:40:31 IDT" name="testUpdateAccessPublicToPrivate" finished-at="2025-04-29T21:40:42 IDT" duration-ms="10392" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateAccessPublicToPrivate -->
      </class> <!-- UpdateAccessTests -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
